from __future__ import annotations

# Rule-based expense categorization based on `description` text.
#
# Edit these lists over time as you discover more merchants/strings.
# Matching is case-insensitive and uses simple substring checks.

EXPENSE_CATEGORIES: list[str] = [
    "Groceries",
    "Pet",
    "Ice Hockey",
    "Fuel",
    "Car service",
    "Maintenance",
    "Transport",
    "Eat Out",
    "Shopping",
    # Placeholders / common buckets
    "Bills",
    "Subscriptions",
    "Health",
    "Entertainment",
    "Travel",
    "Home",
    "Insurance",
    "Bank fees",
    "Gifts",
    "Other",
]

# Ordered rules: first match wins.
# Keep more specific rules earlier.
EXPENSE_CATEGORY_RULES: list[tuple[str, list[str]]] = [
    (
        "Groceries",
        [
            "carlsro bageri aps",
            "parkman",
            "normal",
            "lygten bazar",
            "sct. peders bageri & konditori",
            "bagt",
            "imi 2610 aps",
            "netto",
            "rema",
            "rema 1000",
            "føtex",
            "foetex",
            "bilka",
            "lidl",
            "aldi",
            "superbrugsen",
            "fakta",
            "kvickly",
            "meny",
            "spar",
            "coop",
            "irma",
            "nemlig",
            "nemlig.com",
            "wolt market",
            "Kaffekapslen",
            "Mob.pay Nan Lygten",
        ],
    ),
    (
        "Pet",
        [
            "zooplus",
            "maxizoo",
            "maxi zoo",
            "pet",
            "dyre",
            "dyrlæge",
            "dyrlaege",
            "vet",
            "veterinary",
        ],
    ),
    (
        "Ice Hockey",
        [
            "skatertown aps",
            "holdsport",
            "kjobenhavns skojt",
            "hockey",
            "ice hockey",
            "ishockey",
            "skøjte",
            "skoejte",
            "rink",
        ],
    ),
    (
        "Fuel",
        [
            "uno-x",
            "uno x",
            "aral",
            "totalenergies",
            "circle k",
            "shell",
            "q8",
            "ok ",
            "esso",
            "tank",
            "fuel",
            "benzin",
            "diesel",
        ],
    ),
    (
        "Car service",
        [
            "værksted",
            "vaerksted",
            "service",
            "mechanic",
            "dæk",
            "daek",
            "tire",
            "tyre",
            "car wash",
            "wash",
            "synshal",
        ],
    ),
    (
        "Maintenance",
        [
            "thansen",
            "tein foto roedovre aps",
        ],
    ),
    (
        "Transport",
        [
            "dsb",
            "metro",
            "rejsekort",
            "bus",
            "train",
            "uber",
            "bolt",
            "taxi",
            "parking",
            "parkering",
            "p-hus",
        ],
    ),
    (
        "Eat Out",
        [
            "det gronne kokken rodo",
            "wolt",
            "just eat",
            "justeat",
            "foodora",
            "restaurant",
            "cafe",
            "coffee",
            "pizza",
            "burger",
            "sushi",
            "mcdonald",
            "kebab",
            "bar ",
        ],
    ),
    (
        "Shopping",
        [
            "amazon",
            "ikea",
            "zara",
            "h&m",
            "hm ",
            "asos",
            "elgiganten",
            "power",
            "apple",
            "store",
            "shop",
            "Zalando Payments",
            "JYSK",
            "Nike",
        ],
    ),
    (
        "Subscriptions",
        [
            "spotify",
            "netflix",
            "hbo",
            "disney",
            "prime",
            "youtube premium",
            "google",
            "icloud",
            "microsoft",
        ],
    ),
    (
        "Bills",
        [
            "electric",
            "el ",
            "internet",
            "broadband",
            "mobile",
            "phone",
            "telia",
            "telenor",
            "3 ",
            "water",
            "utility",
        ],
    ),
    (
        "Health",
        [
            "odontologijos klinika",
            "apotek",
            "pharmacy",
            "doctor",
            "dentist",
            "tandlæge",
            "tandlaege",
            "hospital",
            "Comfortclic",
        ],
    ),
    (
        "Insurance",
        [
            "insurance",
            "forsikring",
        ],
    ),
    (
        "Bank fees",
        [
            "fee",
            "commission",
            "charges",
        ],
    ),
    (
        "Travel",
        [
            "brobizz",
            "dm drogerie",
            "edeka",
            "tk maxx",
            "pop mart",
            "faraos live",
            "c&a",
            "schuhpark",
            "lihn warnsdorf skorepa",
            "emsgalerie",
            "hotel",
            "airbnb",
            "flight",
            "ryanair",
            "easyjet",
            "sas",
            "norwegian",
        ],
    ),
    (
        "Entertainment",
        [
            "cinema",
            "movie",
            "concert",
            "museum",
            "game",
            "Fafla Mikroverk",
        ],
    ),
    (
        "Home",
        [
            "furniture",
            "hardware",
            "jem & fix",
            "bauhaus",
            "silvan",
            "ikea",
        ],
    ),
    (
        "Gifts",
        [
            "gift",
            "present",
            "flowers",
            "blomster",
        ],
    ),
]

DEFAULT_EXPENSE_CATEGORY = "Other"
